version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y unzip zip
  build:
    commands:
      - zip -r sample-app.zip . -x '*.git*'
      - aws s3 cp sample-app.zip s3://pythonmysqlapp/
